version: '3'

services: 
  mysql1:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
#    volumes:
#      - mysql1:/var/lib/mysql

#volumes:
#  mysql1:
#    driver_opts:
#      type: tmpfs
#      device: tmpfs
