version: "3.2"

services:
  clickhouse1:
    image: yandex/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
#    volumes:
#      - ./local.xml:/etc/clickhouse-server/config.d/local.xml
