version: "3.3"

services:

  tarantool1:
    image: tarantool/tarantool:latest # 2.8.2 
    # x.x.0 = alpha, x.x.1 = beta, x.x.2+ = stable, latest not always stable
    volumes:
      - ./tarantool-data:/usr/local/share/tarantool
    ports:
      - "3301:3301"
